### ISSUE TITLE
[Feature Request] A select Namespace argument

### ISSUE THREAD

**Issue by GameDungeon** [scottrogowski/code2flow#46]
Currently, in my project, I just care about how a couple of classes interact with each other. Using code2flow has been an amazing way to see just how they are connected and show it to others. The issue is I've had to write a script that gets every other namespace to ignore with the exceptions of the ones I want. The ability to say, I want a graph with just these classes would be amazing.

**Comment by scottrogowski** [comment]
Hi @GameDungeon 

To confirm, code2flow has a --exclude-namespaces argument. This doesn't work for you because you only care about one or two namespaces. Instead, you would want something like an --only-namespaces argument where you can include a few comma separated namespaces? I see the usefulness but want to ensure I'm understanding the request. Would a --only-functions argument also be useful for your use case?

**Comment by GameDungeon** [comment]
That's exactly right. Maybe instead of --only-functions, you could add the comma separation for --target-function.

**Comment by scottrogowski** [comment]
Got it. --target-function serves a different purpose and the CLI is getting a bit hairy as-is so I don't think I want to overload that. I'll have to think about the best way to do it. Will let you know when I do. Might be a week or two or three unfortunately.

**Comment by scottrogowski** [comment]
Turned out to be 3 months. PR is up. It would be helpful to get a second set of eyes on it: https://github.com/scottrogowski/code2flow/pull/54.

**Comment by scottrogowski** [comment]
Just released as v2.5. Let me know if you have any issues.
