### ISSUE TITLE
Thoughts on making JS prototypes work

### ISSUE THREAD

**Issue by aidanhs** [scottrogowski/code2flow#5]
It'd be nice if prototypes worked correctly.
But there's the question of how they'd be represented on the graph.

Just to think out loud, this would possibly require code2flow to be able to differentiate between object methods (e.g. toString) and normal functions.
This would then allow the graph to represent _which_ object method is being called (e.g. if a class overrode the Object.toString method, that could be represented.

One thing I'm curious about is your decision to 'home-grow' the regular expressions etc - have you deliberately decided not to use existing tools (say uglifyjs) to generate an AST and work from there?
On a related note, have you seen https://github.com/abort/javascript-call-graph?

Just pondering on the most appropriate tool for the job at the moment.

**Comment by codeanit** [comment]
Interesting conversation @scottrogowski, @aidanhs 😃  

I am doing some research on domain - language parsers. 
As came to know about code2flow, it was exciting to
know that you are looking forward to work further in this 
project Scott.

There are many opensource projects from individuals
and bigger organizations most of them trying to set some 
standard protocols for generating abstract syntax tree
that would help analyze the code better. `Sourcetrail`
and `Sourcegraph` projects are few of the most significant
projects I seen till now and both relies on some other
third-party technologies but code2graph is taking a
different path from the core, custom JS and Python 
parsers.

I am curious to know about your current view  on the 
statement you made a while ago - `I didn't investigate 
language specific tools since I wanted code2flow to be 
language-agnostic`. Did you consider investigating other 
tools? 

I am trying to figure out the best way to generalize the 
AST generation process for multiple languages and be
able to store the information which would later be used
for doing some analysis and visualize them, such as 
their interdependence via a call graph.   

I have not reviewed the code thoroughly enough to 
understand if code2flow generates a generic AST
for both JS and Python code. 

I will be looking forward to your thoughts Scott.

Thank you for making code2flow opensource.

**Comment by scottrogowski** [comment]
Hi Anit,

Thank you for reaching out. It's encouraging to see how much interest there still is in code2flow even after all of these years. 

So to answer your first question, code2flow doesn't use ASTs internally and I don't think the rewrite will either.

I'll also revise a statement that I made in 2014: 

> "The challenge is more about identifying all of the ways in which prototypes get instantiated and inherited. It is definitely surmountable"

Now, seven years later and seven years wiser, I don't believe it is surmountable. Python and Javascript (and Ruby and PHP, which I'm also now working on) all are dynamic languages with duck typing. It is impossible to know before running your code what type any individual variable will be. To take a toy example, consider this:
```
if random.random() < .5:
    var_a = ClassX()
else:
    var_a = ClassY()
```
Given this toy example, for languages with duck typing, we can't ever hope to achieve a perfect call graph. I haven't worked in static languages in a while but my understanding is that if this were done in Java/C/Go etc, any subsequent method calls on var_a would result in a compile-time error unless the method signature was the same for both ClassX and ClassY. This makes static call-graph analysis possible and relatively easy - which is what is happening with SourceTrail.

It turns out though, in practice, that you will often get situations like this in dynamic languages:
```
var_a = ClassX()
var_a.do_a_thing()
```
In this case, with a few not-even-that-clever heuristics, we can know for certain that the "do_a_thing" we are calling is in ClassX. The magic of code2flow is that it does things like this. You can do enough with regular expressions and heuristics to get pretty good accuracy on most projects.

And I think that's all just a long-winded way to say, I don't think I'll generate ASTs internally because I don't think they'll work better than regular expressions, and while they might be "cleaner" I think they would also be more complicated.

Hopefully, I addressed the points you made? I would be curious to hear more because you seem well informed and I don't always see every angle.

**Comment by codeanit** [comment]
Hi Scott,

Thank you for the detailed and clear answer.

The domain of code analysis and Parsers is large, 
and vague sometimes if we do not understand our 
purpose 😃. My goal was to create a call graph and 
store the information. Having looked at diverse tools 
taking different approaches, was very enriching overall.

Having done some research on Sourcegraph and 
Sourcetrail, and understanding further about their 
use-cases, I believe that the path you are looking 
forward to take leans more  towards Sourcegraph. 
It used to use regular expression previously but 
has some thing advanced now. But it does not 
generate a call graph.

The v2 branch must be the one you are working
on right now. I think updating this in the master
would be helpful for other visitors. Furthermore,
I believe that if there is any plannig documents 
available and the project is more organized then
it would be easier to understand the state and 
even other to contribute. Well I am super interested.

I will be keeping track of things and looking forward 
to seeing interesting usage of this project. And looking
forward to contributing, and trying to figure out how 
I can at the moment.

Thanks again, and good luck.

**Comment by scottrogowski** [comment]
Hey Amit,

I decided, after all, to go with using ASTs internally. So the branch I am working on is AST, https://github.com/scottrogowski/code2flow/tree/ast. It is working for Python but does not yet have the quality of testing I would want to merge into master.  The limitations regarding duck-typing are still present, of course, but it might be more of what you are looking for. Expect a merge into master in the next two weeks.

Thanks for your continued interest! I'm actually going to close this issue since it's so old but feel free to open a new issue or contact me otherwise. Specifically, let me know if you think there are any missing features.

**Comment by codeanit** [comment]
Thank you for your reply @scottrogowski.

I am sure that as you are taking AST path 
is the best path which opens up many 
opportunities in the analysis domain 😃.

The big challenge moving ahead in this path
is to finding what we do with the generated 
AST as many standard open source tools 
exists that others have used. Further more,
I have found in my short research that choosing
the right algorithms to do that would be the next
thing to do where I stopped before. 

I look forward to the new release, and will be 
looking at the branch as well.

Thanks again Scott.
