### ISSUE TITLE
Cannot install code2flow

### ISSUE THREAD

**Issue by JohnCheeKinChow** [scottrogowski/code2flow#65]
Hi, 

I am a real rookie in this, but I want to install code2flow on my macbook with intel chip. but I got some problems.
- First I install code2flow with: pip3 install code2flow. it is installed but when I want to use it for example: code2flow myjavascriptfile.js it says: command not found: code2flow.
- Then I want to install graphviz with brew and I get this error message: Warning: No available formula with the name "graphviz".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
It was migrated from homebrew/cask to homebrew/core.

Can someone help me? Thanks a lot!

**Comment by scottrogowski** [comment]
Hi John,

Sorry for the delay.

A few things. With the installation, you probably need to open a new shell after installing. If that doesn't work, you have issues with your PATH. Search for "troubleshooting PATH issues for Python binaries" or something of that nature.

Graphviz should install with brew https://formulae.brew.sh/formula/graphviz. It's possible you need to run `brew doctor` or otherwise upgrade / reinstall brew.

Let me know if that doesn't help.
